language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

install:
  - pip install --upgrade pip
  - pip install pip-tools
  - pip-compile
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest --cov-report=xml --cov=./makeycli/

after_success:
  - codecov

deploy:
  # deploy develop branch to test pypi
  - provider: pypi
    server: https://test.pypi.org/legacy/
    username: __token__
    password: $PYPI_TEST_TOKEN
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      branch: develop
      python: "3.9"

  # deploy release tag to pypi
  - provider: pypi
    username: __token__
    password: $PYPI_TOKEN
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: "3.9"
